manifest:
  remotes:
    - name: duffrind
      url-base: https://github.com/duffrind
  projects:
    - name: zmk
      remote: duffrind
      revision: main
      import: app/west.yml
  self:
    path: config
